### ISSUE TITLE
Metaphlan2 database google drive link not working 

### ISSUE THREAD

**Issue by wasimbt** [pjtorres/metagenomics_tutorial#1]
Hi, 

Thank you for creating such a nice tutorial. Following it, I am not able to download the metaphlan2 customized database from the mentioned google drive link, https://drive.google.com/drive/u/0/folders/1eWR6tgUoAUNXWsFujyLU5VNUzNMfxhDm

Could you please have a look?

Best regards, 
Wasim

**Comment by pjtorres** [comment]
Updated metaphlan2 file location in README file
